apiVersion: v1
kind: Pod
metadata:
  name: emptydir-example
  labels:
    app: file-processor
spec:
  containers:
    - name: writer-container
      image: busybox
      command: ["sh", "-c", "echo 'Hello from writer!' > /shared/data.txt && sleep 3600"]
      volumeMounts:
        - name: shared-storage
          mountPath: /shared
    - name: reader-container
      image: busybox
      command: ['sh', '-c', 'echo "Reading file: " && cat /shared/data.txt && sleep 3600']
      volumeMounts:
        - name: shared-storage
          mountPath: /shared
  
  volumes:
    - name: shared-storage
      emptyDir: 
        sizeLimit: 100Mi