apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
        - name: data
          image: data-service:1.0
          ports:
            - containerPort: 5001
          env:
            - name: REDIS_HOST
              value: "redis-service"


---
apiVersion: v1
kind: Service
metadata:
  name: data-service
spec: 
  selector: 
    app: data
  ports:
    - port: 5001