apiVersion: v1
kind: Pod
metadata:
  name: pv-pvc-example-2
spec:
  containers:
    - name: pv-pvc-container
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
      volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: my-local-pvc
        