apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kube-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-kube-app
  template:
    metadata:
      labels:
        app: my-kube-app
    spec:
      containers:
        - name: my-kube-app
          image: my-kube-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: welcome-message