apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example
  labels:
    app: hostpath-app
spec:
  containers:
    - name: hostpath-container
      image: nginx:alpine
      ports:  
        - containerPort: 80
      volumeMounts:
        - name: hostpath-data
          mountPath: /usr/share/nginx/html
        - name: hostpath-logs
          mountPath: /var/log/nginx
  volumes:
    - name: hostpath-data
      hostPath:
        path: /mnt/k8s-data/html
        type: DirectoryOrCreate
    - name: hostpath-logs
      hostPath:
        path: /mnt/k8s-data/logs
        type: DirectoryOrCreate