apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: projet-debutant
data: 
  app.name: "Mon Application kubernetes"
  app.version: "1.0.0"
  environment: "development"
  log.level: |
    error_log  /var/log/nginx/error.log warn;