apiVersion: v1
kind: ConfigMap
metadata:
  name: health-config
data:
  liveness-test.sh: |
    #!/bin/sh
    if [ -f /tmp/healthy ]; then
      echo "OK"
      exit 0
    else
      echo "Not OK"
      exit 1
    fi